### PR TITLE
Refactoring Arduino library

### PR DESCRIPTION
**Pull request by sosandroid**
Making the library more straight forward

### CODE REVIEW

**Comment by AmarOk1412** [comment]
I tried this library this morning. And it works :+1:

**Comment by sosandroid** [comment]
Thanks for the feedback !

**Comment by renzoe** [comment]
Hi just to check with Wi6labs (sosandroid are you from wi6labs?)
Requesting permission to merge this pull request (seems not to break anything)

**Comment by sosandroid** [comment]
@renzoe I'm not from Wi6labs othewise I would have publish straight the code into their repository.

By the way, I'm planning to propose more examples in near future.

**Pull request merged**
